### ISSUE TITLE
“Memory Model: 从多处理器到高级语言” 似乎存在笔误？

### ISSUE THREAD

**Issue by goteet** [GHScan/TechNotes#2]
Non-FIFI 是 Non-FIFO 么？还是只是我理解错误了。如果是后者，可以烦请给一些简单的解释么？十分感谢。

> Store-Store Order：当CPU和Cache间有一个**Non-FIFI**或Coalescing的写缓冲时，如果前一个写操作导致Cache Miss或和其他写操作合并(因为写同一条Cache Line)，后一条结果可能先写入Cache。如果Memory Model或Barrier指令限制这种乱序，则要求采用FIFO的写缓冲，或在遇到Barrier指令时Flush整个写缓冲

**Comment by GHScan** [comment]
你的理解是对的，是笔误。

**Comment by GHScan** [comment]
已修复
